I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\renpy-7.3.5-sdk\renpy\main.py", line 534, in main
    renpy.dump.dump(False)
  File "C:\renpy-7.3.5-sdk\renpy\dump.py", line 255, in dump
    os.rename(new, args.json_dump)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Vampire in Bottineau 1.0
Thu Jun 04 09:15:18 2020
